// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVvbKZpAiKMTp0WwgoPfynJV-gh9BMz_M',
    appId: '1:360355824770:web:07bf27645dfb603e15209b',
    messagingSenderId: '360355824770',
    projectId: 'tegauto-573df',
    authDomain: 'tegauto-573df.firebaseapp.com',
    storageBucket: 'tegauto-573df.appspot.com',
    measurementId: 'G-22E42EZDWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPdN3RIfqoOsZZL0T3vb4JgeRIDgg82jg',
    appId: '1:360355824770:android:1ba3c95e66cd1ea515209b',
    messagingSenderId: '360355824770',
    projectId: 'tegauto-573df',
    storageBucket: 'tegauto-573df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPXPZ2P2bUh5rTgE6Y82hBOEBa2B2sMh0',
    appId: '1:360355824770:ios:55ecd038a48401c515209b',
    messagingSenderId: '360355824770',
    projectId: 'tegauto-573df',
    storageBucket: 'tegauto-573df.appspot.com',
    iosClientId: '360355824770-594jotalb3u8ff7vj623mghp5ol86nh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tegAuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPXPZ2P2bUh5rTgE6Y82hBOEBa2B2sMh0',
    appId: '1:360355824770:ios:55ecd038a48401c515209b',
    messagingSenderId: '360355824770',
    projectId: 'tegauto-573df',
    storageBucket: 'tegauto-573df.appspot.com',
    iosClientId: '360355824770-594jotalb3u8ff7vj623mghp5ol86nh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tegAuto',
  );
}
